# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

# To keep us on latest since maintainer stopped releasing versions
[[constraint]]
  name = "github.com/hashicorp/memberlist"
  branch = "master"

# To avoid pulling old gorp version, we use master of our fork
[[constraint]]
  name = "github.com/mattermost/gorp"
  branch = "master"

# Fork for adding our own method to viper EnvSettings
[[constraint]]
  name = "github.com/mattermost/viper"
  source = "https://github.com/mattermost/viper"
  branch = "mattermost"

# Keep back because of breaking API changes
[[constraint]]
  name = "github.com/segmentio/analytics-go"
  version = "2.1.1"

# Use latest master since we rely on some security features that don't exist in latest release
[[constraint]]
  name = "willnorris.com/go/imageproxy"
  branch = "master"

# Lock to control when plugins use new versions
[[constraint]]
  name = "github.com/hashicorp/go-hclog"
  revision = "e45cbeb79f0411b1cfedd3f226ff69d5d433c762"

[[constraint]]
  name = "github.com/hashicorp/go-plugin"
  revision = "54b6ff97d8180dbbd93d2010dd4a92c86f604bb8"

[prune]
  go-tests = true
  unused-packages = true
